version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ntprdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - C:/docker/ntpr-mysql-data:/var/lib/mysql

  api:
    build: ./api
    container_name: api
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ntprdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"

  core:
    build: ./core
    container_name: core
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8081/api/v1/
    ports:
      - "8080:8080"
